# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-23 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('nav', models.FloatField()),
                ('cav', models.FloatField()),
                ('rate', models.FloatField()),
            ],
        ),
    ]
